services:
  # ─── backend API ─────────────────────────────────
  - name: dashboard-api
    type: web
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app

  # ─── legacy React UI (still uses npm) ───────────
  - name: dashboard-legacy-ui
    type: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build          # CRA outputs build/

  # ─── new React UI (uses Yarn) ───────────────────
  - name: dashboard-materialauszug
    type: static
    rootDir: materialauszug
    buildCommand: yarn install --frozen-lockfile && yarn build
    staticPublishPath: build          # react-scripts outputs build/