services:
  - name: dashboard-api
    type: web
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
  - name: dashboard-legacy-ui
    type: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
  - name: dashboard-materialauszug
    type: static          # or web if it needs SSR
    rootDir: materialauszug
    buildCommand: npm ci && npm run build
    staticPublishPath: dist   # change to your actual directory